### ISSUE TITLE
Top 2 submissions or top 2 methods?

### ISSUE THREAD

**Issue by TroyVan** [TroyVan/STAT-8051-Project#22]
We get to pick 2 submissions for the final score. What if, as is currently the case, the 2 highest-scoring submissions are from the same method? Should we pick the top 2 scoring _methods_ or the top 2 _submissions_?

**Comment by TroyVan** [comment]
The last 10 submissions are all by @vtao1989, and all perform better than previous submissions.

From the instructions on Kaggle:

> Your final score may not be based on the same exact subset of data as the public leaderboard, but rather a different private data subset of your full submission — your public score is only a rough indication of what your final score is.
> 
> You should thus choose submissions that will most likely be best overall, and not necessarily on the public subset.

The choices need to be made today; otherwise the top two scoring submissions will be automatically selected.

**Comment by vtao1989** [comment]
The deadline for the competition is tomorrow at 10 pm. We could still try a little bit.

You could select them at 9:30 pm tomorrow. I guess using the top two will be a better choice.

**Comment by vtao1989** [comment]
@TroyVan I guess 10 pm is for UTC time. So you could choose the best two now.

**Comment by TroyVan** [comment]
I somehow miscounted the date. There are 21 hours left, which means that closing time is tomorrow at 4 pm Central Time.
Again, if we're going with top 2 submissions, there is no need for me to pick.

**Comment by TroyVan** [comment]
Check that, it's 10 pm Central Time now. Which means we have 6 submission slots left: 3 now and 3 after 6 pm.

**Comment by vtao1989** [comment]
@TroyVan I am worried about my current model with too many variables will lead to overfitting in the leaderboard. I will try a little bit and tell you which two to select, might not be the best two.

**Comment by vtao1989** [comment]
@TroyVan I've done! Keep using the highest two. Thanks!

**Comment by TroyVan** [comment]
I have selected the top 2 scoring submissions. It looks like I can change my choices before closing time (10 pm). Actual (private leaderboard) scores won't be announced before closing.

**Comment by TroyVan** [comment]
The competition has closed and we won. Congratulations and good job @vtao1989.

Now we need to do a good presentation to secure the win, so get those slides in and don't relax yet.
