### ISSUE TITLE
About meetings

### ISSUE THREAD

**Issue by TroyVan** [TroyVan/STAT-8051-Project#7]
I don't expect to call meetings until near the end, for practicing the presentation. Before then, we should be able to do all the work electronically, and as I said before, real-time meetings often result in miscommunication.

That said, I'm open to holding meetings if the need arises. Such meetings, however, should not result in big decisions, which should be considered carefully across a period of time, not in the heat of the moment.

**In view of the foregoing, if would be helpful if everyone could inform me, either under this post or privately be email, of your availability schedule for the duration of the project (up to and including Wednesday September 4).**

**Comment by vtao1989** [comment]
Hi Tory. Four of us discussed and we found that tomorrow 4 - 5 pm is a good time for a meeting. Are you available during that time? I heard that you live nearby. Hopefully, it works for you. Thanks.
