### ISSUE TITLE
Kaggle team building in progress

### ISSUE THREAD

**Issue by TroyVan** [TroyVan/STAT-8051-Project#8]
Kaggle only allows one pending team invite at a time, so I have to wait for the current invite to be accepted before I can send out another. Please promptly respond to Kaggle invites as you receive them.

@matthewfazio - completed
@Celeste1114 - completed
@vtao1989 - completed
@hezhou1354 - completed

**Comment by TroyVan** [comment]
@vtao1989 Your turn now. Please check Kaggle.

**Comment by matthewfazio** [comment]
*matthewfazio is my Kaggle name as well.

**Comment by TroyVan** [comment]
@hezhou1354 @matthewfazio I cannot find you by name. I need your "Team Name", listed at https://www.kaggle.com/c/mn2019comp/team, which should default to your **screen name**, not your username. Please double check that the names you have given me are correct.

**Comment by matthewfazio** [comment]
User name is matthewfazio and display name is Matthew Fazio.

**Comment by TroyVan** [comment]
Then I have some problem on my part because I cannot look you up for some reason. Normally when I type in a name, a dropdown list should appear listing matching names. No dropdown means no match.
![](https://user-images.githubusercontent.com/31454917/68815374-d89c0a80-0640-11ea-98c2-562079c3bba2.png)
Perhaps it's because there has been a submission to the leaderboard today. I'll give it some time and try again; if it still doesn't work, I'll have to take it up with the competition organizers.

**Comment by Celeste1114** [comment]
https://www.kaggle.com/c/homesite-quote-conversion
