### ISSUE TITLE
Can not commit to master

### ISSUE THREAD

**Issue by vtao1989** [TroyVan/STAT-8051-Project#9]
Hi Troy,

Could you fix this? Thanks.

Tao

**Comment by TroyVan** [comment]
@vtao1989 You need to accept the invitation at https://github.com/TroyVan/STAT-8051-Project/invitations in order to get write access.

**Comment by TroyVan** [comment]
Same goes for @matthewfazio.

**Comment by matthewfazio** [comment]
User name is Matthew Fazio.

**Comment by TroyVan** [comment]
@matthewfazio Is this not the account you want to use? As far as I know GitHub usernames cannot contain spaces. If this is your account, go ahead and take the invitation at https://github.com/TroyVan/STAT-8051-Project/invitations.

**Comment by matthewfazio** [comment]
*Username for Kaggle

**Comment by TroyVan** [comment]
@matthewfazio Thanks, you're now in the queue. Do take care of the GitHub invitation in the meantime.
